//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPool.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewEditCarResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewEditCarResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarPool.App.Resources.Texts.NewEditCarResources", typeof(NewEditCarResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD YOUR CAR.
        /// </summary>
        public static string Add_Heading_Content {
            get {
                return ResourceManager.GetString("Add_Heading_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO BACK.
        /// </summary>
        public static string Back_Button {
            get {
                return ResourceManager.GetString("Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Registration.
        /// </summary>
        public static string Date_Content {
            get {
                return ResourceManager.GetString("Date_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT YOUR CAR.
        /// </summary>
        public static string Edit_Heading_Content {
            get {
                return ResourceManager.GetString("Edit_Heading_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer_Content {
            get {
                return ResourceManager.GetString("Manufacturer_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model_Content {
            get {
                return ResourceManager.GetString("Model_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo URL.
        /// </summary>
        public static string Photo_Content {
            get {
                return ResourceManager.GetString("Photo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Plate.
        /// </summary>
        public static string Plate_Content {
            get {
                return ResourceManager.GetString("Plate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Seats.
        /// </summary>
        public static string Seats_Content {
            get {
                return ResourceManager.GetString("Seats_Content", resourceCulture);
            }
        }
    }
}
