//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPool.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewRideResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewRideResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarPool.App.Resources.Texts.NewRideResources", typeof(NewRideResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO BACK.
        /// </summary>
        public static string Back_Button {
            get {
                return ResourceManager.GetString("Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a car.
        /// </summary>
        public static string Car_Content {
            get {
                return ResourceManager.GetString("Car_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string Create_Button {
            get {
                return ResourceManager.GetString("Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add some description.
        /// </summary>
        public static string Description_Content {
            get {
                return ResourceManager.GetString("Description_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected duration.
        /// </summary>
        public static string Duration_Content {
            get {
                return ResourceManager.GetString("Duration_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From_Content {
            get {
                return ResourceManager.GetString("From_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE A NEW RIDE.
        /// </summary>
        public static string Heading_Content {
            get {
                return ResourceManager.GetString("Heading_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To_Content {
            get {
                return ResourceManager.GetString("To_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string When_Content {
            get {
                return ResourceManager.GetString("When_Content", resourceCulture);
            }
        }
    }
}
