//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPool.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserProfileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarPool.App.Resources.Texts.UserProfileResources", typeof(UserProfileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        internal static string About_Content {
            get {
                return ResourceManager.GetString("About_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string Back_Button {
            get {
                return ResourceManager.GetString("Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cars.
        /// </summary>
        internal static string Cars_Content {
            get {
                return ResourceManager.GetString("Cars_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string Date_Content {
            get {
                return ResourceManager.GetString("Date_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVE.
        /// </summary>
        internal static string Drive_Button {
            get {
                return ResourceManager.GetString("Drive_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email_Content {
            get {
                return ResourceManager.GetString("Email_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From_Content {
            get {
                return ResourceManager.GetString("From_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        internal static string Heading_Content {
            get {
                return ResourceManager.GetString("Heading_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_Content {
            get {
                return ResourceManager.GetString("Name_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string New_Car_Button {
            get {
                return ResourceManager.GetString("New_Car_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone_Content {
            get {
                return ResourceManager.GetString("Phone_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIDE.
        /// </summary>
        internal static string Ride_Button {
            get {
                return ResourceManager.GetString("Ride_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Rides.
        /// </summary>
        internal static string Rides_Content {
            get {
                return ResourceManager.GetString("Rides_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To_Content {
            get {
                return ResourceManager.GetString("To_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string When_Content {
            get {
                return ResourceManager.GetString("When_Content", resourceCulture);
            }
        }
    }
}
